//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerFarmService.RExService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RExService.IRExService")]
    public interface IRExService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRExService/Exec", ReplyAction="http://tempuri.org/IRExService/ExecResponse")]
        int Exec(ulong taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRExService/IsProcessRunning", ReplyAction="http://tempuri.org/IRExService/IsProcessRunningResponse")]
        bool IsProcessRunning(int pid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRExServiceChannel : ControllerFarmService.RExService.IRExService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RExServiceClient : System.ServiceModel.ClientBase<ControllerFarmService.RExService.IRExService>, ControllerFarmService.RExService.IRExService {
        
        public RExServiceClient() {
        }
        
        public RExServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RExServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RExServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RExServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Exec(ulong taskId) {
            return base.Channel.Exec(taskId);
        }
        
        public bool IsProcessRunning(int pid) {
            return base.Channel.IsProcessRunning(pid);
        }
    }
}
