//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceProxies.AccountingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Notification", Namespace="http://escience.ifmo.ru/easis/eventing")]
    [System.SerializableAttribute()]
    public partial class Notification : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceProxies.AccountingService.EventReport EventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceProxies.AccountingService.SubscriptionId SubscriptionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProxies.AccountingService.EventReport Event {
            get {
                return this.EventField;
            }
            set {
                if ((object.ReferenceEquals(this.EventField, value) != true)) {
                    this.EventField = value;
                    this.RaisePropertyChanged("Event");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProxies.AccountingService.SubscriptionId SubscriptionId {
            get {
                return this.SubscriptionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SubscriptionIdField, value) != true)) {
                    this.SubscriptionIdField = value;
                    this.RaisePropertyChanged("SubscriptionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag {
            get {
                return this.TagField;
            }
            set {
                if ((object.ReferenceEquals(this.TagField, value) != true)) {
                    this.TagField = value;
                    this.RaisePropertyChanged("Tag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventReport", Namespace="http://escience.ifmo.ru/easis/eventing")]
    [System.SerializableAttribute()]
    public partial class EventReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchemeUriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TopicField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchemeUri {
            get {
                return this.SchemeUriField;
            }
            set {
                if ((object.ReferenceEquals(this.SchemeUriField, value) != true)) {
                    this.SchemeUriField = value;
                    this.RaisePropertyChanged("SchemeUri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source {
            get {
                return this.SourceField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceField, value) != true)) {
                    this.SourceField = value;
                    this.RaisePropertyChanged("Source");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Topic {
            get {
                return this.TopicField;
            }
            set {
                if ((object.ReferenceEquals(this.TopicField, value) != true)) {
                    this.TopicField = value;
                    this.RaisePropertyChanged("Topic");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubscriptionId", Namespace="http://escience.ifmo.ru/easis/eventing")]
    [System.SerializableAttribute()]
    public partial class SubscriptionId : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryRecord", Namespace="http://schemas.datacontract.org/2004/07/Easis.BillingLibs")]
    [System.SerializableAttribute()]
    public partial class HistoryRecord : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceProxies.AccountingService.HistoryAction HistoryActionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WfIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProxies.AccountingService.HistoryAction HistoryActionType {
            get {
                return this.HistoryActionTypeField;
            }
            set {
                if ((this.HistoryActionTypeField.Equals(value) != true)) {
                    this.HistoryActionTypeField = value;
                    this.RaisePropertyChanged("HistoryActionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WfId {
            get {
                return this.WfIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WfIdField, value) != true)) {
                    this.WfIdField = value;
                    this.RaisePropertyChanged("WfId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoryAction", Namespace="http://schemas.datacontract.org/2004/07/Easis.BillingLibs")]
    public enum HistoryAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Withdraw = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deposite = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reserve = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateInfo", Namespace="http://schemas.datacontract.org/2004/07/Easis.BillingLibs")]
    [System.SerializableAttribute()]
    public partial class RateInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ServiceProxies.AccountingService.ObjectId IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PackageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResourceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.EndTimeField, value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceProxies.AccountingService.ObjectId Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackageName {
            get {
                return this.PackageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PackageNameField, value) != true)) {
                    this.PackageNameField = value;
                    this.RaisePropertyChanged("PackageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceName {
            get {
                return this.ResourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceNameField, value) != true)) {
                    this.ResourceNameField = value;
                    this.RaisePropertyChanged("ResourceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.StartTimeField, value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectId", Namespace="http://schemas.datacontract.org/2004/07/MongoDB.Bson")]
    [System.SerializableAttribute()]
    public partial struct ObjectId : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int incrementField;
        
        private int machineField;
        
        private short pidField;
        
        private int timestampField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int increment {
            get {
                return this.incrementField;
            }
            set {
                if ((this.incrementField.Equals(value) != true)) {
                    this.incrementField = value;
                    this.RaisePropertyChanged("increment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int machine {
            get {
                return this.machineField;
            }
            set {
                if ((this.machineField.Equals(value) != true)) {
                    this.machineField = value;
                    this.RaisePropertyChanged("machine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short pid {
            get {
                return this.pidField;
            }
            set {
                if ((this.pidField.Equals(value) != true)) {
                    this.pidField = value;
                    this.RaisePropertyChanged("pid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int timestamp {
            get {
                return this.timestampField;
            }
            set {
                if ((this.timestampField.Equals(value) != true)) {
                    this.timestampField = value;
                    this.RaisePropertyChanged("timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountingService.IBillingService")]
    public interface IBillingService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://escience.ifmo.ru/easis/eventing) of message NotifyRequest does not match the default value (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="http://escience.ifmo.ru/easis/eventing/Notify", ReplyAction="http://escience.ifmo.ru/easis/eventing/INotifiable/NotifyResponse")]
        ServiceProxies.AccountingService.NotifyResponse Notify(ServiceProxies.AccountingService.NotifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/Calculate", ReplyAction="http://tempuri.org/IBillingService/CalculateResponse")]
        double Calculate(ulong taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/CalculateList", ReplyAction="http://tempuri.org/IBillingService/CalculateListResponse")]
        double CalculateList(ulong[] taskIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/CheckPossibility", ReplyAction="http://tempuri.org/IBillingService/CheckPossibilityResponse")]
        bool CheckPossibility(ulong taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/CheckPossibilityList", ReplyAction="http://tempuri.org/IBillingService/CheckPossibilityListResponse")]
        bool CheckPossibilityList(ulong[] taskIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/CalculateAndWithdraw", ReplyAction="http://tempuri.org/IBillingService/CalculateAndWithdrawResponse")]
        void CalculateAndWithdraw(ulong taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillingService/CalculateAndWithdrawWf", ReplyAction="http://tempuri.org/IBillingService/CalculateAndWithdrawWfResponse")]
        void CalculateAndWithdrawWf(System.Guid wfId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Notify", WrapperNamespace="http://escience.ifmo.ru/easis/eventing", IsWrapped=true)]
    public partial class NotifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://escience.ifmo.ru/easis/eventing", Order=0)]
        public ServiceProxies.AccountingService.Notification notification;
        
        public NotifyRequest() {
        }
        
        public NotifyRequest(ServiceProxies.AccountingService.Notification notification) {
            this.notification = notification;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NotifyResponse", WrapperNamespace="http://escience.ifmo.ru/easis/eventing", IsWrapped=true)]
    public partial class NotifyResponse {
        
        public NotifyResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBillingServiceChannel : ServiceProxies.AccountingService.IBillingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillingServiceClient : System.ServiceModel.ClientBase<ServiceProxies.AccountingService.IBillingService>, ServiceProxies.AccountingService.IBillingService {
        
        public BillingServiceClient() {
        }
        
        public BillingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceProxies.AccountingService.NotifyResponse ServiceProxies.AccountingService.IBillingService.Notify(ServiceProxies.AccountingService.NotifyRequest request) {
            return base.Channel.Notify(request);
        }
        
        public void Notify(ServiceProxies.AccountingService.Notification notification) {
            ServiceProxies.AccountingService.NotifyRequest inValue = new ServiceProxies.AccountingService.NotifyRequest();
            inValue.notification = notification;
            ServiceProxies.AccountingService.NotifyResponse retVal = ((ServiceProxies.AccountingService.IBillingService)(this)).Notify(inValue);
        }
        
        public double Calculate(ulong taskId) {
            return base.Channel.Calculate(taskId);
        }
        
        public double CalculateList(ulong[] taskIds) {
            return base.Channel.CalculateList(taskIds);
        }
        
        public bool CheckPossibility(ulong taskId) {
            return base.Channel.CheckPossibility(taskId);
        }
        
        public bool CheckPossibilityList(ulong[] taskIds) {
            return base.Channel.CheckPossibilityList(taskIds);
        }
        
        public void CalculateAndWithdraw(ulong taskId) {
            base.Channel.CalculateAndWithdraw(taskId);
        }
        
        public void CalculateAndWithdrawWf(System.Guid wfId) {
            base.Channel.CalculateAndWithdrawWf(wfId);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountingService.IAccountingService")]
    public interface IAccountingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountingService/GetUserQuotingInfo", ReplyAction="http://tempuri.org/IAccountingService/GetUserQuotingInfoResponse")]
        double GetUserQuotingInfo(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountingService/GetHistory", ReplyAction="http://tempuri.org/IAccountingService/GetHistoryResponse")]
        ServiceProxies.AccountingService.HistoryRecord[] GetHistory(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountingService/Withdraw", ReplyAction="http://tempuri.org/IAccountingService/WithdrawResponse")]
        void Withdraw(string user, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountingService/Deposite", ReplyAction="http://tempuri.org/IAccountingService/DepositeResponse")]
        void Deposite(string user, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountingService/Reserve", ReplyAction="http://tempuri.org/IAccountingService/ReserveResponse")]
        bool Reserve(string user, double amount, string wfid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAccountingService/Dereserve", ReplyAction="http://tempuri.org/IAccountingService/DereserveResponse")]
        void Dereserve(string user, double amount, string wfid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAccountingServiceChannel : ServiceProxies.AccountingService.IAccountingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountingServiceClient : System.ServiceModel.ClientBase<ServiceProxies.AccountingService.IAccountingService>, ServiceProxies.AccountingService.IAccountingService {
        
        public AccountingServiceClient() {
        }
        
        public AccountingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AccountingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AccountingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double GetUserQuotingInfo(string username) {
            return base.Channel.GetUserQuotingInfo(username);
        }
        
        public ServiceProxies.AccountingService.HistoryRecord[] GetHistory(string username) {
            return base.Channel.GetHistory(username);
        }
        
        public void Withdraw(string user, double amount) {
            base.Channel.Withdraw(user, amount);
        }
        
        public void Deposite(string user, double amount) {
            base.Channel.Deposite(user, amount);
        }
        
        public bool Reserve(string user, double amount, string wfid) {
            return base.Channel.Reserve(user, amount, wfid);
        }
        
        public void Dereserve(string user, double amount, string wfid) {
            base.Channel.Dereserve(user, amount, wfid);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AccountingService.ITarrifingService")]
    public interface ITarrifingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITarrifingService/SetRate", ReplyAction="http://tempuri.org/ITarrifingService/SetRateResponse")]
        void SetRate(ServiceProxies.AccountingService.RateInfo rateInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITarrifingServiceChannel : ServiceProxies.AccountingService.ITarrifingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TarrifingServiceClient : System.ServiceModel.ClientBase<ServiceProxies.AccountingService.ITarrifingService>, ServiceProxies.AccountingService.ITarrifingService {
        
        public TarrifingServiceClient() {
        }
        
        public TarrifingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TarrifingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TarrifingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TarrifingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetRate(ServiceProxies.AccountingService.RateInfo rateInfo) {
            base.Channel.SetRate(rateInfo);
        }
    }
}
