//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoadingEmulator.SchedulerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskScheduler.Workflow", Namespace="http://schemas.datacontract.org/2004/07/Scheduler")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LoadingEmulator.SchedulerServiceReference.TaskSchedulerUrgentWorkflow))]
    public partial class TaskSchedulerWorkflow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.TaskSchedulerActiveTask[] ActiveTasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OptimizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.Resource[] ResourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.TaskSchedulerTask[] TasksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.TaskSchedulerActiveTask[] ActiveTasks {
            get {
                return this.ActiveTasksField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveTasksField, value) != true)) {
                    this.ActiveTasksField = value;
                    this.RaisePropertyChanged("ActiveTasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Optimize {
            get {
                return this.OptimizeField;
            }
            set {
                if ((this.OptimizeField.Equals(value) != true)) {
                    this.OptimizeField = value;
                    this.RaisePropertyChanged("Optimize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.Resource[] Resources {
            get {
                return this.ResourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourcesField, value) != true)) {
                    this.ResourcesField = value;
                    this.RaisePropertyChanged("Resources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.TaskSchedulerTask[] Tasks {
            get {
                return this.TasksField;
            }
            set {
                if ((object.ReferenceEquals(this.TasksField, value) != true)) {
                    this.TasksField = value;
                    this.RaisePropertyChanged("Tasks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskScheduler.UrgentWorkflow", Namespace="http://schemas.datacontract.org/2004/07/Scheduler")]
    [System.SerializableAttribute()]
    public partial class TaskSchedulerUrgentWorkflow : LoadingEmulator.SchedulerServiceReference.TaskSchedulerWorkflow {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxExecutionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinExecutionTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxExecutionTime {
            get {
                return this.MaxExecutionTimeField;
            }
            set {
                if ((this.MaxExecutionTimeField.Equals(value) != true)) {
                    this.MaxExecutionTimeField = value;
                    this.RaisePropertyChanged("MaxExecutionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinExecutionTime {
            get {
                return this.MinExecutionTimeField;
            }
            set {
                if ((this.MinExecutionTimeField.Equals(value) != true)) {
                    this.MinExecutionTimeField = value;
                    this.RaisePropertyChanged("MinExecutionTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskScheduler.ActiveTask", Namespace="http://schemas.datacontract.org/2004/07/Scheduler")]
    [System.SerializableAttribute()]
    public partial class TaskSchedulerActiveTask : LoadingEmulator.SchedulerServiceReference.TaskSchedulerTask {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.LaunchDestination DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EstimatedLaunchTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.EstimationResult EstimationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUrgentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.TaskSchedulerTaskState StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.LaunchDestination Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EstimatedLaunchTime {
            get {
                return this.EstimatedLaunchTimeField;
            }
            set {
                if ((this.EstimatedLaunchTimeField.Equals(value) != true)) {
                    this.EstimatedLaunchTimeField = value;
                    this.RaisePropertyChanged("EstimatedLaunchTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.EstimationResult Estimation {
            get {
                return this.EstimationField;
            }
            set {
                if ((object.ReferenceEquals(this.EstimationField, value) != true)) {
                    this.EstimationField = value;
                    this.RaisePropertyChanged("Estimation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUrgent {
            get {
                return this.IsUrgentField;
            }
            set {
                if ((this.IsUrgentField.Equals(value) != true)) {
                    this.IsUrgentField = value;
                    this.RaisePropertyChanged("IsUrgent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.TaskSchedulerTaskState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resource", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    public partial class Resource : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.Node[] NodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.Node[] Nodes {
            get {
                return this.NodesField;
            }
            set {
                if ((object.ReferenceEquals(this.NodesField, value) != true)) {
                    this.NodesField = value;
                    this.RaisePropertyChanged("Nodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskScheduler.Task", Namespace="http://schemas.datacontract.org/2004/07/Scheduler")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LoadingEmulator.SchedulerServiceReference.TaskSchedulerActiveTask))]
    public partial class TaskSchedulerTask : LoadingEmulator.SchedulerServiceReference.TaskSchedulerBaseTask {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.LaunchDestination[] SuitableDestinationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.LaunchDestination[] SuitableDestinations {
            get {
                return this.SuitableDestinationsField;
            }
            set {
                if ((object.ReferenceEquals(this.SuitableDestinationsField, value) != true)) {
                    this.SuitableDestinationsField = value;
                    this.RaisePropertyChanged("SuitableDestinations");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskScheduler.BaseTask", Namespace="http://schemas.datacontract.org/2004/07/Scheduler")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LoadingEmulator.SchedulerServiceReference.ActiveEstimatedTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LoadingEmulator.SchedulerServiceReference.EstimatedTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LoadingEmulator.SchedulerServiceReference.TaskSchedulerTask))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LoadingEmulator.SchedulerServiceReference.TaskSchedulerActiveTask))]
    public partial class TaskSchedulerBaseTask : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ulong IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ulong Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveEstimatedTask", Namespace="http://schemas.datacontract.org/2004/07/Scheduler.Estimated")]
    [System.SerializableAttribute()]
    public partial class ActiveEstimatedTask : LoadingEmulator.SchedulerServiceReference.TaskSchedulerBaseTask {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.ActiveEstimation EstimationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsUrgentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MonopolizeResourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.TaskSchedulerTaskState StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.ActiveEstimation Estimation {
            get {
                return this.EstimationField;
            }
            set {
                if ((object.ReferenceEquals(this.EstimationField, value) != true)) {
                    this.EstimationField = value;
                    this.RaisePropertyChanged("Estimation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUrgent {
            get {
                return this.IsUrgentField;
            }
            set {
                if ((this.IsUrgentField.Equals(value) != true)) {
                    this.IsUrgentField = value;
                    this.RaisePropertyChanged("IsUrgent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MonopolizeResource {
            get {
                return this.MonopolizeResourceField;
            }
            set {
                if ((this.MonopolizeResourceField.Equals(value) != true)) {
                    this.MonopolizeResourceField = value;
                    this.RaisePropertyChanged("MonopolizeResource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.TaskSchedulerTaskState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstimatedTask", Namespace="http://schemas.datacontract.org/2004/07/Scheduler.Estimated")]
    [System.SerializableAttribute()]
    public partial class EstimatedTask : LoadingEmulator.SchedulerServiceReference.TaskSchedulerBaseTask {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.ResourceEstimation[] EstimationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.ResourceEstimation[] Estimations {
            get {
                return this.EstimationsField;
            }
            set {
                if ((object.ReferenceEquals(this.EstimationsField, value) != true)) {
                    this.EstimationsField = value;
                    this.RaisePropertyChanged("Estimations");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LaunchDestination", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    public partial class LaunchDestination : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] NodeNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResourceNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] NodeNames {
            get {
                return this.NodeNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.NodeNamesField, value) != true)) {
                    this.NodeNamesField = value;
                    this.RaisePropertyChanged("NodeNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceName {
            get {
                return this.ResourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceNameField, value) != true)) {
                    this.ResourceNameField = value;
                    this.RaisePropertyChanged("ResourceName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstimationResult", Namespace="http://schemas.datacontract.org/2004/07/TimeMeter")]
    [System.SerializableAttribute()]
    public partial class EstimationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CalculationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OverheadsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.EstimationResult.ParameterValue[] ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double CalculationTime {
            get {
                return this.CalculationTimeField;
            }
            set {
                if ((this.CalculationTimeField.Equals(value) != true)) {
                    this.CalculationTimeField = value;
                    this.RaisePropertyChanged("CalculationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Overheads {
            get {
                return this.OverheadsField;
            }
            set {
                if ((this.OverheadsField.Equals(value) != true)) {
                    this.OverheadsField = value;
                    this.RaisePropertyChanged("Overheads");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.EstimationResult.ParameterValue[] Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="EstimationResult.ParameterValue", Namespace="http://schemas.datacontract.org/2004/07/TimeMeter")]
        [System.SerializableAttribute()]
        public partial struct ParameterValue : System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string InitialValueField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string NameField;
            
            [System.Runtime.Serialization.OptionalFieldAttribute()]
            private string NewValueField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string InitialValue {
                get {
                    return this.InitialValueField;
                }
                set {
                    if ((object.ReferenceEquals(this.InitialValueField, value) != true)) {
                        this.InitialValueField = value;
                        this.RaisePropertyChanged("InitialValue");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string Name {
                get {
                    return this.NameField;
                }
                set {
                    if ((object.ReferenceEquals(this.NameField, value) != true)) {
                        this.NameField = value;
                        this.RaisePropertyChanged("Name");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute()]
            public string NewValue {
                get {
                    return this.NewValueField;
                }
                set {
                    if ((object.ReferenceEquals(this.NewValueField, value) != true)) {
                        this.NewValueField = value;
                        this.RaisePropertyChanged("NewValue");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskScheduler.TaskState", Namespace="http://schemas.datacontract.org/2004/07/Scheduler")]
    public enum TaskSchedulerTaskState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LAUNCHED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCHEDULED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ABORTED = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveEstimation", Namespace="http://schemas.datacontract.org/2004/07/Scheduler.Estimated")]
    [System.SerializableAttribute()]
    public partial class ActiveEstimation : LoadingEmulator.SchedulerServiceReference.ResourceEstimation {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.LaunchDestination DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LaunchTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.LaunchDestination Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double LaunchTime {
            get {
                return this.LaunchTimeField;
            }
            set {
                if ((this.LaunchTimeField.Equals(value) != true)) {
                    this.LaunchTimeField = value;
                    this.RaisePropertyChanged("LaunchTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceEstimation", Namespace="http://schemas.datacontract.org/2004/07/Scheduler.Estimated")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LoadingEmulator.SchedulerServiceReference.ActiveEstimation))]
    public partial class ResourceEstimation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.Resource ResourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.EstimationResult ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.Resource Resource {
            get {
                return this.ResourceField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceField, value) != true)) {
                    this.ResourceField = value;
                    this.RaisePropertyChanged("Resource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.EstimationResult Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Node", Namespace="http://schemas.datacontract.org/2004/07/Common")]
    [System.SerializableAttribute()]
    public partial class Node : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoresAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CoresTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNSNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResourceNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoresAvailable {
            get {
                return this.CoresAvailableField;
            }
            set {
                if ((this.CoresAvailableField.Equals(value) != true)) {
                    this.CoresAvailableField = value;
                    this.RaisePropertyChanged("CoresAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoresTotal {
            get {
                return this.CoresTotalField;
            }
            set {
                if ((this.CoresTotalField.Equals(value) != true)) {
                    this.CoresTotalField = value;
                    this.RaisePropertyChanged("CoresTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNSName {
            get {
                return this.DNSNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DNSNameField, value) != true)) {
                    this.DNSNameField = value;
                    this.RaisePropertyChanged("DNSName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceName {
            get {
                return this.ResourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ResourceNameField, value) != true)) {
                    this.ResourceNameField = value;
                    this.RaisePropertyChanged("ResourceName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskScheduler.LaunchPlan", Namespace="http://schemas.datacontract.org/2004/07/Scheduler")]
    [System.SerializableAttribute()]
    public partial class TaskSchedulerLaunchPlan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EstimatedExecutionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.TaskSchedulerActiveTask[] PlanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EstimatedExecutionTime {
            get {
                return this.EstimatedExecutionTimeField;
            }
            set {
                if ((this.EstimatedExecutionTimeField.Equals(value) != true)) {
                    this.EstimatedExecutionTimeField = value;
                    this.RaisePropertyChanged("EstimatedExecutionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.TaskSchedulerActiveTask[] Plan {
            get {
                return this.PlanField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanField, value) != true)) {
                    this.PlanField = value;
                    this.RaisePropertyChanged("Plan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstimatedWorkflow", Namespace="http://schemas.datacontract.org/2004/07/Scheduler.Estimated")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LoadingEmulator.SchedulerServiceReference.EstimatedUrgentWorkflow))]
    public partial class EstimatedWorkflow : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.ActiveEstimatedTask[] ActiveTasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.TasksDepenendency[] DependenciesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OptimizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.EstimatedTask[] TasksField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.ActiveEstimatedTask[] ActiveTasks {
            get {
                return this.ActiveTasksField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveTasksField, value) != true)) {
                    this.ActiveTasksField = value;
                    this.RaisePropertyChanged("ActiveTasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.TasksDepenendency[] Dependencies {
            get {
                return this.DependenciesField;
            }
            set {
                if ((object.ReferenceEquals(this.DependenciesField, value) != true)) {
                    this.DependenciesField = value;
                    this.RaisePropertyChanged("Dependencies");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Optimize {
            get {
                return this.OptimizeField;
            }
            set {
                if ((this.OptimizeField.Equals(value) != true)) {
                    this.OptimizeField = value;
                    this.RaisePropertyChanged("Optimize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.EstimatedTask[] Tasks {
            get {
                return this.TasksField;
            }
            set {
                if ((object.ReferenceEquals(this.TasksField, value) != true)) {
                    this.TasksField = value;
                    this.RaisePropertyChanged("Tasks");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstimatedUrgentWorkflow", Namespace="http://schemas.datacontract.org/2004/07/Scheduler.Estimated")]
    [System.SerializableAttribute()]
    public partial class EstimatedUrgentWorkflow : LoadingEmulator.SchedulerServiceReference.EstimatedWorkflow {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MaxExecutionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MinExecutionTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxExecutionTime {
            get {
                return this.MaxExecutionTimeField;
            }
            set {
                if ((this.MaxExecutionTimeField.Equals(value) != true)) {
                    this.MaxExecutionTimeField = value;
                    this.RaisePropertyChanged("MaxExecutionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MinExecutionTime {
            get {
                return this.MinExecutionTimeField;
            }
            set {
                if ((this.MinExecutionTimeField.Equals(value) != true)) {
                    this.MinExecutionTimeField = value;
                    this.RaisePropertyChanged("MinExecutionTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TasksDepenendency", Namespace="http://schemas.datacontract.org/2004/07/Scheduler.Estimated")]
    [System.SerializableAttribute()]
    public partial class TasksDepenendency : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ulong ConsumerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ulong ProviderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong ConsumerId {
            get {
                return this.ConsumerIdField;
            }
            set {
                if ((this.ConsumerIdField.Equals(value) != true)) {
                    this.ConsumerIdField = value;
                    this.RaisePropertyChanged("ConsumerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong ProviderId {
            get {
                return this.ProviderIdField;
            }
            set {
                if ((this.ProviderIdField.Equals(value) != true)) {
                    this.ProviderIdField = value;
                    this.RaisePropertyChanged("ProviderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LaunchPlan", Namespace="http://schemas.datacontract.org/2004/07/Scheduler.Estimated")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(LoadingEmulator.SchedulerServiceReference.UrgentPlan))]
    public partial class LaunchPlan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EstimatedExecutionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.TaskSchedulerNodeAvailabilityTime[] NodesTimingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LoadingEmulator.SchedulerServiceReference.ActiveEstimatedTask[] PlanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EstimatedExecutionTime {
            get {
                return this.EstimatedExecutionTimeField;
            }
            set {
                if ((this.EstimatedExecutionTimeField.Equals(value) != true)) {
                    this.EstimatedExecutionTimeField = value;
                    this.RaisePropertyChanged("EstimatedExecutionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.TaskSchedulerNodeAvailabilityTime[] NodesTimings {
            get {
                return this.NodesTimingsField;
            }
            set {
                if ((object.ReferenceEquals(this.NodesTimingsField, value) != true)) {
                    this.NodesTimingsField = value;
                    this.RaisePropertyChanged("NodesTimings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LoadingEmulator.SchedulerServiceReference.ActiveEstimatedTask[] Plan {
            get {
                return this.PlanField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanField, value) != true)) {
                    this.PlanField = value;
                    this.RaisePropertyChanged("Plan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UrgentPlan", Namespace="http://schemas.datacontract.org/2004/07/Scheduler.Estimated")]
    [System.SerializableAttribute()]
    public partial class UrgentPlan : LoadingEmulator.SchedulerServiceReference.LaunchPlan {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskScheduler.NodeAvailabilityTime", Namespace="http://schemas.datacontract.org/2004/07/Scheduler")]
    [System.SerializableAttribute()]
    public partial class TaskSchedulerNodeAvailabilityTime : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchedulerServiceReference.ISchedulerService")]
    public interface ISchedulerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/Reschedule", ReplyAction="http://tempuri.org/IScheduler/RescheduleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/RescheduleErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        LoadingEmulator.SchedulerServiceReference.TaskSchedulerLaunchPlan Reschedule(LoadingEmulator.SchedulerServiceReference.TaskSchedulerWorkflow workflow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/RescheduleEstimated", ReplyAction="http://tempuri.org/IScheduler/RescheduleEstimatedResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/RescheduleEstimatedErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        LoadingEmulator.SchedulerServiceReference.LaunchPlan RescheduleEstimated(LoadingEmulator.SchedulerServiceReference.EstimatedWorkflow workflow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/CreateTestWF", ReplyAction="http://tempuri.org/IScheduler/CreateTestWFResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/CreateTestWFErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        LoadingEmulator.SchedulerServiceReference.TaskSchedulerWorkflow CreateTestWF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/RescheduleUrgent", ReplyAction="http://tempuri.org/IScheduler/RescheduleUrgentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/RescheduleUrgentErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        LoadingEmulator.SchedulerServiceReference.TaskSchedulerLaunchPlan RescheduleUrgent(LoadingEmulator.SchedulerServiceReference.TaskSchedulerUrgentWorkflow workflow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/CreateUrgentTestWF", ReplyAction="http://tempuri.org/IScheduler/CreateUrgentTestWFResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/CreateUrgentTestWFErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        LoadingEmulator.SchedulerServiceReference.TaskSchedulerUrgentWorkflow CreateUrgentTestWF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetClusterNames", ReplyAction="http://tempuri.org/IScheduler/GetClusterNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/GetClusterNamesErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        string[] GetClusterNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetAppNames", ReplyAction="http://tempuri.org/IScheduler/GetAppNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/GetAppNamesErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        string[] GetAppNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetDefaultUHName", ReplyAction="http://tempuri.org/IScheduler/GetDefaultUHNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/GetDefaultUHNameErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        string GetDefaultUHName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetUHNames", ReplyAction="http://tempuri.org/IScheduler/GetUHNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/GetUHNamesErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        string[] GetUHNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/SetDefaultUHName", ReplyAction="http://tempuri.org/IScheduler/SetDefaultUHNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/SetDefaultUHNameErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        void SetDefaultUHName(string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetDefaultHName", ReplyAction="http://tempuri.org/IScheduler/GetDefaultHNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/GetDefaultHNameErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        string GetDefaultHName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/GetHNames", ReplyAction="http://tempuri.org/IScheduler/GetHNamesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/GetHNamesErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        string[] GetHNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScheduler/SetDefaultHName", ReplyAction="http://tempuri.org/IScheduler/SetDefaultHNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Testing.VMSrv.ErrorMessage), Action="http://tempuri.org/IScheduler/SetDefaultHNameErrorMessageFault", Name="ErrorMessage", Namespace="http://schemas.datacontract.org/2004/07/Common")]
        void SetDefaultHName(string newName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchedulerServiceChannel : LoadingEmulator.SchedulerServiceReference.ISchedulerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchedulerServiceClient : System.ServiceModel.ClientBase<LoadingEmulator.SchedulerServiceReference.ISchedulerService>, LoadingEmulator.SchedulerServiceReference.ISchedulerService {
        
        public SchedulerServiceClient() {
        }
        
        public SchedulerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchedulerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LoadingEmulator.SchedulerServiceReference.TaskSchedulerLaunchPlan Reschedule(LoadingEmulator.SchedulerServiceReference.TaskSchedulerWorkflow workflow) {
            return base.Channel.Reschedule(workflow);
        }
        
        public LoadingEmulator.SchedulerServiceReference.LaunchPlan RescheduleEstimated(LoadingEmulator.SchedulerServiceReference.EstimatedWorkflow workflow) {
            return base.Channel.RescheduleEstimated(workflow);
        }
        
        public LoadingEmulator.SchedulerServiceReference.TaskSchedulerWorkflow CreateTestWF() {
            return base.Channel.CreateTestWF();
        }
        
        public LoadingEmulator.SchedulerServiceReference.TaskSchedulerLaunchPlan RescheduleUrgent(LoadingEmulator.SchedulerServiceReference.TaskSchedulerUrgentWorkflow workflow) {
            return base.Channel.RescheduleUrgent(workflow);
        }
        
        public LoadingEmulator.SchedulerServiceReference.TaskSchedulerUrgentWorkflow CreateUrgentTestWF() {
            return base.Channel.CreateUrgentTestWF();
        }
        
        public string[] GetClusterNames() {
            return base.Channel.GetClusterNames();
        }
        
        public string[] GetAppNames() {
            return base.Channel.GetAppNames();
        }
        
        public string GetDefaultUHName() {
            return base.Channel.GetDefaultUHName();
        }
        
        public string[] GetUHNames() {
            return base.Channel.GetUHNames();
        }
        
        public void SetDefaultUHName(string newName) {
            base.Channel.SetDefaultUHName(newName);
        }
        
        public string GetDefaultHName() {
            return base.Channel.GetDefaultHName();
        }
        
        public string[] GetHNames() {
            return base.Channel.GetHNames();
        }
        
        public void SetDefaultHName(string newName) {
            base.Channel.SetDefaultHName(newName);
        }
    }
}
