//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControllerFarmService.ExtFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExtFileService.IFileStreamService")]
    public interface IFileStreamService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileStreamService/SendFileAsStream", ReplyAction="http://tempuri.org/IFileStreamService/SendFileAsStreamResponse")]
        ControllerFarmService.ExtFileService.SendFileAsStreamResponse SendFileAsStream(ControllerFarmService.ExtFileService.FileStreamedMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileStreamService/SendFileChunkAsStream", ReplyAction="http://tempuri.org/IFileStreamService/SendFileChunkAsStreamResponse")]
        ControllerFarmService.ExtFileService.SendFileChunkAsStreamResponse SendFileChunkAsStream(ControllerFarmService.ExtFileService.ChunkedFileStreamedMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileStreamService/GetFileAsStream", ReplyAction="http://tempuri.org/IFileStreamService/GetFileAsStreamResponse")]
        ControllerFarmService.ExtFileService.GetFileAsStreamResponse GetFileAsStream(ControllerFarmService.ExtFileService.GetFileAsStreamRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileStreamService/GetFileChunkAsStream", ReplyAction="http://tempuri.org/IFileStreamService/GetFileChunkAsStreamResponse")]
        ControllerFarmService.ExtFileService.GetFileChunkAsStreamResponse GetFileChunkAsStream(ControllerFarmService.ExtFileService.GetFileChunkAsStreamRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileStreamedMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileStreamedMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FarmId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream Stream;
        
        public FileStreamedMessage() {
        }
        
        public FileStreamedMessage(string FarmId, string FileName, string Id, System.IO.Stream Stream) {
            this.FarmId = FarmId;
            this.FileName = FileName;
            this.Id = Id;
            this.Stream = Stream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFileAsStreamResponse {
        
        public SendFileAsStreamResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ChunkedFileStreamedMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ChunkedFileStreamedMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int ChunkSize;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FarmId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string FileName;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public int FilePart;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream Stream;
        
        public ChunkedFileStreamedMessage() {
        }
        
        public ChunkedFileStreamedMessage(int ChunkSize, string FarmId, string FileName, int FilePart, string Id, System.IO.Stream Stream) {
            this.ChunkSize = ChunkSize;
            this.FarmId = FarmId;
            this.FileName = FileName;
            this.FilePart = FilePart;
            this.Id = Id;
            this.Stream = Stream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendFileChunkAsStreamResponse {
        
        public SendFileChunkAsStreamResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileAsStream", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileAsStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ulong taskId;
        
        public GetFileAsStreamRequest() {
        }
        
        public GetFileAsStreamRequest(string path, ulong taskId) {
            this.path = path;
            this.taskId = taskId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileAsStreamResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileAsStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream GetFileAsStreamResult;
        
        public GetFileAsStreamResponse() {
        }
        
        public GetFileAsStreamResponse(System.IO.Stream GetFileAsStreamResult) {
            this.GetFileAsStreamResult = GetFileAsStreamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileChunkAsStream", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileChunkAsStreamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fpath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public ulong taskId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int chunkNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int chunkSize;
        
        public GetFileChunkAsStreamRequest() {
        }
        
        public GetFileChunkAsStreamRequest(string fpath, ulong taskId, int chunkNum, int chunkSize) {
            this.fpath = fpath;
            this.taskId = taskId;
            this.chunkNum = chunkNum;
            this.chunkSize = chunkSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFileChunkAsStreamResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFileChunkAsStreamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream GetFileChunkAsStreamResult;
        
        public GetFileChunkAsStreamResponse() {
        }
        
        public GetFileChunkAsStreamResponse(System.IO.Stream GetFileChunkAsStreamResult) {
            this.GetFileChunkAsStreamResult = GetFileChunkAsStreamResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileStreamServiceChannel : ControllerFarmService.ExtFileService.IFileStreamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileStreamServiceClient : System.ServiceModel.ClientBase<ControllerFarmService.ExtFileService.IFileStreamService>, ControllerFarmService.ExtFileService.IFileStreamService {
        
        public FileStreamServiceClient() {
        }
        
        public FileStreamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileStreamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileStreamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileStreamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ControllerFarmService.ExtFileService.SendFileAsStreamResponse SendFileAsStream(ControllerFarmService.ExtFileService.FileStreamedMessage request) {
            return base.Channel.SendFileAsStream(request);
        }
        
        public ControllerFarmService.ExtFileService.SendFileChunkAsStreamResponse SendFileChunkAsStream(ControllerFarmService.ExtFileService.ChunkedFileStreamedMessage request) {
            return base.Channel.SendFileChunkAsStream(request);
        }
        
        public ControllerFarmService.ExtFileService.GetFileAsStreamResponse GetFileAsStream(ControllerFarmService.ExtFileService.GetFileAsStreamRequest request) {
            return base.Channel.GetFileAsStream(request);
        }
        
        public ControllerFarmService.ExtFileService.GetFileChunkAsStreamResponse GetFileChunkAsStream(ControllerFarmService.ExtFileService.GetFileChunkAsStreamRequest request) {
            return base.Channel.GetFileChunkAsStream(request);
        }
    }
}
